# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Dactyl Carbonfet'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["dactyl_carbonfet_left","dactyl_carbonfet_right"]'

